### ISSUE TITLE
Enhancement: upgrade to terra while doing geospatial operations 

### ISSUE THREAD

**Issue by Rapsodia86** [VangiElia/GEDI4R#4]
Hello,
So I have been working with the package since yesterday; it is great so thank you very much for your work!
I wanted to ask if you are planning any upgrades to the package?
If so, I would like to suggest switching from raster & sf to terra (https://github.com/rspatial/terra)
For my other site
```
coords
      ymax       ymin       xmin       xmax 
  40.49909   39.07442 -105.48687 -103.60604 
```
for 2019, when using `l4_getmulti`, I ended up with a data.table of length: 31628747. I tried to `l4_clip` it with my buffer and it has been suuper long and never finished. Therefore I switched to terra and it has been a moment, like this:

```
l4_v <- terra::vect(l4,geom=c("lon_lowestmode","lat_lowestmode"), crs="EPSG:4326", keepgeom=FALSE) #or keepgeom=TRUE
l4_vm <- terra::mask(l4_v, buf1p, inverse=FALSE)
```

Thanks again!

**Comment by VangiElia** [comment]
Hi, 
Thank you for the suggestion. I am aware of the new updated terra package, and already for some time, I have been thinking of updating GEDI4R by replacing the raster and sf functions with terra. And I will do it, I promise :) But in this period I'am really busy. I hope to be able to do it in my spare time in the next few months. 
Glad the package its useful for you

**Comment by Rapsodia86** [comment]
Great! Thanks!:)
